*******************************************************************************
****** Askisi schematic exam_4348  <vs>  Askisi layout exam_4348
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(N_12_LLRVT) MOS                                  4       4
(P_12_LLRVT) MOS                                  4       4
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_12_LLRVT) MOS                                  4       4           2       2
(P_12_LLRVT) MOS                                  4       4           0       0
(N_12_LLRVT:SerMos2#1) MosBlk                     -       -           1       1
(P_12_LLRVT:ParMos2#1) MosBlk                     -       -           1       1
(P_12_LLRVT:SerMos4#1) MosBlk                     -       -           1       1
                                             ------  ------      ------  ------
Total                                             8       8           5       5

Schematic and Layout Match
