*******************************************************************************
****** NAND schematic MyDesignLib  <vs>  NAND layout MyDesignLib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(N_12_LLRVT) MOS                                  2       2
(P_12_LLRVT) MOS                                  2       2
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_12_LLRVT) MOS                                  2       2           0       0
(P_12_LLRVT) MOS                                  2       2           0       0
(N_12_LLRVT:SerMos2#1) MosBlk                     -       -           1       1
(P_12_LLRVT:ParMos2#1) MosBlk                     -       -           1       1
                                             ------  ------      ------  ------
Total                                             4       4           2       2

Schematic and Layout Match
